<?php

$functions_text = array (

'notifyfrom'			=>	'Notifica&ccedil;&atilde;o do:',
'autogenerated'			=>	'ESTA &Eacute; UMA MENSAGEM GERADA AUTOMATICAMENTE, N&Atilde;O RESPONDA',
'back'					=>	'Voltar',
'forward'				=>	'Pr&oacute;xima',

);
?>