<?php

// Tłumaczenie na języki polski
// Translation to Polish
//
// Tomek 'TomasH' Zielinski
// tomash@fidonet.org.pl, tomash@4net.pl

$functions_text = array (

'notifyfrom'	=>	'Powiadomienie od',
'autogenerated'	=>	'WIADOMOŚĆ WYGENEROWANA AUTOMATYCZNIE, NIE ODPOWIADAJ NA NIĄ',
'back'		=>	'Wróć',
'forward'	=>	'Prześlij',

);
// vim:fenc=utf-8:enc=utf-8
?>
