<?php

// Tłumaczenie na języki polski
// Translation to Polish
//
// Tomek 'TomasH' Zielinski
// tomash@fidonet.org.pl, tomash@4net.pl

$functions_text = array (

'notifyfrom'	=>	'Powiadomienie od',
'autogenerated'	=>	'WIADOMOŚĆ WYGENEROWANA AUTOMATYCZNIE, NIE ODPOWIADAJ NA NIĄ',
'back'		=>	'Wróć',
'forward'	=>	'Prześlij',

// Added in version 0.9.8
'previous'              =>    'Poprzednia',
'next'                  =>    'Następna',
'first'                 =>    'Pierwsza',
'last'                  =>    'Ostatnia',
'page'                  =>    'Strona %d z %d',

);
// vim:fenc=utf-8:enc=utf-8
?>
