<?php

global $functions_text;
$functions_text = array (

'notifyfrom'            =>    'Notification from Flyspray',  // Changed in version 0.9.8
'autogenerated'         =>    'THIS IS AN AUTOMATICALLY GENERATED MESSAGE, DO NOT REPLY',
'back'                  =>    'Back',        // Not longer used
'forward'                               =>      'Forward',     // Not longer used

// Added in version 0.9.8
'previous'              =>    'Previous',
'next'                  =>    'Next',
'first'                 =>    'First',
'last'                  =>    'Last',
'page'                  =>    'Page %d of %d',

);
?>
