<?php

global $functions_text;
$functions_text = array (

'notifyfrom'			=>	'Notification from',
'autogenerated'			=>	'THIS IS AN AUTOMATICALLY GENERATED MESSAGE, DO NOT REPLY',
'back'					=>	'Back',
'forward'				=>	'Forward',

);
?>
