<?php

global $functions_text;
$functions_text = array (

'notifyfrom'		=>	'Notification de',
'autogenerated'		=>	'CE MESSAGE A ETE GENERE AUTOMATIQUEMENT, NE PAS REPONDRE',
'back'				=>	'Précédent',
'forward'			=>	'Suivant',

);
?>
