<?php

$functions_text = array (

'notifyfrom'			=>	'Notification de',
'autogenerated'			=>	'	CECI EST UN MESSAGE AUTOMATIQUE, NE PAS REPONDRE',
'back'					=>	'Retour',
'forward'				=>	'Avance',

);
?>
