<?php

global $functions_text;
$functions_text = array (

'notifyfrom'    =>  'Nachricht von',
'autogenerated' =>  'Dies ist eine automatisch erstellte Nachricht. Bitte antworten Sie nicht darauf.',
'back'          =>  'Zurück',
'forward'       =>  'Vorwärts'

);
?>
