<?php

$functions_text = array (

'notifyfrom'      =>  'Nachricht von',
'autogenerated'   =>  'DIES IST EINE AUTOMATISCH ERSTELLTE NACHRICHT. ANTWORTEN SIE NICHT DARAUF!',
'back'          =>  'Zurück',
'forward'       =>  'Vorwärts'

);
?>
