<?php

global $functions_text;
$functions_text = array (

'notifyfrom'    =>  'Nachricht von',
'autogenerated' =>  'Dies ist eine automatisch erstellte Nachricht. Bitte antworten Sie nicht darauf.',
'back'          =>  'Zurück',
'forward'       =>  'Vorwärts',

// Added in version 0.9.8
'previous'              =>    'Vorherige',
'next'                  =>    'Nächste',
'first'                 =>    'Erste',
'last'                  =>    'Letze',
'page'                  =>    'Seite %d von %d',

);
?>
