<?php

$functions_text = array (

'notifyfrom'			=>	'Bericht van',
'autogenerated'			=>	'DIT IS EEN AUTOMATISCH BERICHT, NIET ANTWOORDEN AUB',
'back'					=>	'Terug',
'forward'				=>	'Vooruit',

);
?>
