<?php

global $functions_text;
$functions_text = array (

'notifyfrom'            =>    'Bericht van',
'autogenerated'         =>    'DIT IS EEN AUTOMATISCH BERICHT, NIET ANTWOORDEN AUB',
'back'                  =>    'Terug',
'forward'               =>    'Vooruit',

// Added in version 0.9.8
'previous'              =>    'Vorige',
'next'                  =>    'Volgende',
'first'                 =>    'Eerste',
'last'                  =>    'Laatste',
'page'                  =>    'Pagina %d van %d',

);
?>
