<?php

global $functions_text;
$functions_text = array (

'notifyfrom'			=>	'Form di notifica',
'autogenerated'			=>	'QUESTO E\' UN MESSAGGIO GENERATO AUTOMATICAMENTE, NON FARE REPLY',
'back'					=>	'Indietro',
'forward'				=>	'Avanti',

);
?>
