<?php

global $functions_text;
$functions_text = array (

'notifyfrom'			=>	'Notificación de',
'autogenerated'			=>	'ESTE ES UN MENSAJE GENERADO AUTOMATICAMENTE. NO LO RESPONDA.',
'back'					=>	'Atrás',
'forward'				=>	'Adelante',

);
?>
