<?php

global $functions_text;
$functions_text = array (

'notifyfrom'           =>   'Notificacion de',
'autogenerated'        =>   'ESTE ES UN MENSAJE GENERADO AUTOMATICAMENTE. NO LO RESPONDA.',
'back'                 =>   'Atras',
'forward'              =>   'Adelante',

// Added in version 0.9.8
'previous'              =>    'Anterior',
'next'                  =>    'Siguiente',
'first'                 =>    'Primero',
'last'                  =>    'Ultimo',
'page'                  =>    'Pagina %d de %d',

);
?>
