<?php

// Translation to Danish by: Michael S. Müller <msm(at)dbio(dot)dk>

$functions_text = array (

'notifyfrom'			=>	'Meddelelse fra',
'autogenerated'			=>	'DETTE ER EN AUTOMATISK GENERET BESKED, BESVAR DEN VENLIGST IKKE',
'back'					=>	'Tilbage',
'forward'				=>	'Frem',

);
?>
