<?php

/*
 *
 * Svensk översättning av Flyspray:
 * Holger Gremminger
 * info@gremminger.de
 * www.gremminger.de
 * 
 */

global $functions_text;
$functions_text = array (

'notifyfrom'    =>  'Meddelande från',
'autogenerated' =>  'Detta är ett meddelande som har genererats automatiskt. Svara ej på detta meddelande.',
'back'          =>  'Bakåt',
'forward'       =>  'Framåt'

);
?>